[package]
name = "raytracing"
version = "0.1.0"
authors = ["pjmlp <pjmlp@progtools.org>"]
edition = "2021"

[workspace]

[dependencies.utils]
path = "libs/utils"

# External dependencies

[dependencies]
glam = "0.20.2"
image = "0.23.14"
